---
- hosts: unbound
  become: yes
  gather_facts: yes
  vars:
    local_hostnames:
      - example.com
      - example.org
      - example.net
    local_ns_domains:
      - domain.example.com
      - domain.example.org
      - domain.example.net
    localhost_A_record_template:
      type: A
      class: IN
      ttl: 300
      ip_address: 127.0.1.42
      ptr: yes
    localhost_A_records: "{{ local_hostnames | map('replace_field', localhost_A_record_template, 'name') | list }}"
    localhost_NS_record_template:
      type: NS
      class: IN
      ttl: 300000
      rdata: localhost.ns.example.com
    localhost_NS_records: "{{ local_ns_domains | map('replace_field', localhost_NS_record_template, 'name') | list }}"

    unbound_local_data: "{{ localhost_NS_records + localhost_A_records }}"
  roles:
    - "{{ playbook_dir  }}"
