---
- hosts: unbound
  become: yes
  gather_facts: yes
  vars:
    unbound_local_data:
      -
        names:
          - example.com
          - example.org
          - example.net
        type: A
        class: IN
        ttl: 300
        ip_address: 127.0.1.42
        ptr: yes
  roles:
    - "{{ playbook_dir  }}"
