---
- name: Load a variable file based on the OS type, or a default if not found
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - default.yml
      paths: ../vars

- name: add repository signing keys
  apt_key:
    id: "{{ item }}"
    keyserver: keyserver.ubuntu.com
  with_items:
    - 6FBBE07B
    - E5267A6C

- name: add apt repositories
  apt_repository: repo={{ item }}
  with_items:
    - ppa:ondrej/unbound
    - ppa:ondrej/pkg-nlnetlabs

- name: install package from apt (xenial)
  apt:
    name: "{{ unbound_package }}"
    update_cache: yes
    cache_valid_time: 1800
  register: unbound_installed

- name: ensure pid file exists
  copy:
    content: ''
    dest: /run/unbound.pid
    force: no

- name: set correct user/group for pid
  file:
    path: /run/unbound.pid
    owner: root
    group: root

- name: download root hints from internic
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
  register: unbound_root_hints

- name: install configuration file to use root-hints
  copy:
    src: etc/unbound/unbound.conf.d/root-hints.conf.j2
    dest: /etc/unbound/unbound.conf.d/root-hints.conf
  notify: restart unbound

- name: install custom configs from templates
  template:
    src: "{{ item }}"
    dest: /etc/unbound/unbound.conf.d/{{ item | basename | replace('.j2', '') }}
  with_items: "{{ unbound_custom_configuration_files }}"
  notify: restart unbound

- name: disable dnssec
  lineinfile:
    path: /etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf
    regexp: '^(?!.*(#)).*auto-trust-anchor-file'
    line: '#    auto-trust-anchor-file: "/var/lib/unbound/root.key"'
    backrefs: yes
  notify: restart unbound
  when: disable_dnssec

