---
- include: repositories.yml
  when: ansible_lsb.codename in ['trusty', 'xenial']

- name: Hold back version of unbound on xenial because of a package bug
  set_fact:
    unbound_apt_package: unbound=1.5.8-1ubuntu1
  when: ansible_lsb.codename == 'xenial'

- name: install package from apt (trusty)
  apt:
    name: "{{ unbound_apt_package }}"
    update_cache: yes
    cache_valid_time: 1800
  register: unbound_installed

- name: ensure pid file exists
  copy:
    content: ''
    dest: /run/unbound.pid
    force: no

- name: set correct user/group for pid
  file:
    path: /run/unbound.pid
    owner: root
    group: root

- name: download root hints from internic
  get_url:
    url: https://www.internic.net/domain/named.cache
    dest: /etc/unbound/root.hints
  register: unbound_root_hints

- name: install configuration file to use root-hints
  copy:
    src: etc/unbound/unbound.conf.d/root-hints.conf.j2
    dest: /etc/unbound/unbound.conf.d/root-hints.conf
  notify: restart unbound

- name: install custom configs from templates
  template:
    src: "{{ item }}"
    dest: /etc/unbound/unbound.conf.d/{{ item | basename | replace('.j2', '') }}
  with_items: "{{ unbound_custom_configuration_files }}"
  notify: restart unbound
